# This configuration is an example to show Retina in "offline" mode, which
# reads from a PCAP file.
# 
# See https://stanford-esrg.github.io/retina/retina_core/config/index.html
# for configuration options.

main_core = 0
nb_memory_channels = 6

[mempool]
    capacity = 262_144
    cache_size = 512

[offline]
    pcap = "./traces/small_flows.pcap"
    mtu = 9702

[conntrack]
    max_connections = 10_000_000
    max_out_of_order = 500
    timeout_resolution = 100
    udp_inactivity_timeout = 60_000
    tcp_inactivity_timeout = 300_000
    tcp_establish_timeout = 5000
